### ISSUE TITLE
Implementing autoupdate

### ISSUE THREAD

**Issue by sojusnik** [turtl/desktop#14]
An autoupdate feature, upon a new release, would really simplify the update process of the desktop app.

Until there could be a notification, if a new version is available.

**Comment by orthecreedence** [comment]
Both excellent ideas. I think in the next few releases, I'm going to really put in the effort to make the install/update process a lot less painful. Unzipping and running an executable by hand turns out to be a painful process on linux/osx/windows alike. So I'd like to shift some of that work onto the app itself and make installation easier for everyone.

Installers: https://trello.com/c/yrhl8XXU
Auto update: https://trello.com/c/MfrVp8f2
Notification: https://trello.com/c/0kAa6vN6
