### ISSUE TITLE
HiDPI scaling on Linux

### ISSUE THREAD

**Issue by mikebabb** [turtl/desktop#26]
The Linux app works great on a standard resolution monitor, but doesn't currently scale for high resolution displays. Could HiDPI support be added in a future release? See attached for reference.

Thanks!
![screenshot from 2016-03-05 16 36 07](https://cloud.githubusercontent.com/assets/1648598/13548866/e52e2330-e2f1-11e5-9557-005fed64aad8.png)

**Comment by orthecreedence** [comment]
It looks like this is tied to [nw.js](https://github.com/nwjs/nw.js)'s (which is the desktop platform we use to run Turtl). It should be fixed in the beta channel, but I'd rather wait for a stable release as things might break and I'm trying to focus on releasing iOS.

I'm going to leave this issue open until then.

**Comment by mikebabb** [comment]
Thanks for looking in to it! Nice work on the app so far.

**Comment by gaalcaras** [comment]
It works fine for me on my HiDPI screen. Maybe nw.js has been fixed?

**Comment by orthecreedence** [comment]
Yes, I think this has been fixed. Closing (although if it is still an issue, anyone can feel free to reopen).
