### ISSUE TITLE
Default to Edit interface for Notes

### ISSUE THREAD

**Issue by philipashlock** [turtl/desktop#34]
My most frequent behavior when working with Notes is to edit them and I would guess this would be true of most users. However, the current user experience requires me to first click on a note, then view the rendered/preview version, then click edit. Once you're in the edit view, you can click the preview button for a separate preview interface and to go back to the main screen from there you would click back to the edit interface, then click back again to the first preview interface, then finally click back to the main screen. 

I would suggest getting rid of the initial redundant preview interface. Additionally, you might consider providing two buttons on each note from the main screen to either directly edit or preview. 

Here's an animation of going through all the different steps to the preview interface to convey the redundancy of that initial view. 

![turtl-edit](https://cloud.githubusercontent.com/assets/183402/14771073/941004cc-0a4d-11e6-92f6-c5b8b14ea1cf.gif)

**Comment by orthecreedence** [comment]
Thanks for putting in the work to show the workflow you have to go through, this is helpful. I agree that having a way to jump directly into edit is worthwhile. I think on desktop this could be a hover state, and on mobile a long-tap on a note.

I would prefer to keep the preview state because Turtl boards can be very visual when they have images and large amounts of text, and being able to "open" a note makes sense in this context.

That said, I'll add the ability to directly edit. Tracked here:https://trello.com/c/5wZk7ar9
